### ISSUE TITLE
Rename package Lib to Refabricator

### ISSUE THREAD

**Issue by woeps** [woeps/refabricator#5]
Dependents of the library should be able to use it by the actual name.

___

_reported by: @yawaramin on discord: https://discordapp.com/channels/235176658175262720/235198962498273282/676274036711489557_

**Comment by yawaramin** [comment]
Dune works best with the following layout (leaving out the Esy files from here for the moment):

```
<project root>/
  refabricator/
    Refabricator.rei
    // etc.
    dune
  dune-project
  refabricator.opam
```

If you put a `Refabricator.rei`/`Refabricator.re` module inside the `refabricator/` directory, you must manually alias the rest of the modules inside there otherwise dune will treat them as private. If you don't put a module of that name in there, dune will automatically create one and put the modules in there. The former is more explicit but gives you more control e.g. you can put doc comments in the top-level module, as well as other values.
